# 12. час: Модификације табеле и рачунање у табели

На овом часу ћемо говорити о:
1. додавању нове врсте или колоне табели; и
2. транспоновању табеле.

## 12.1. Додавање нове врсте или колоне табели

Понекад је важно да вредности које смо израчунали на основу података у табели (на пример, просеке оцена по ученицима) и сачувамо у табели. Ако табела нема за то предвиђену колону или врсту лако је можемо додати!

Вратимо се поново на пример са оценама ученика кога смо видели на раније:

In [ ]:
# изврши ову ћелију
import pandas as pd
razred = [["Ана",     5, 3, 5, 2, 4, 5],
          ["Бојан",   5, 5, 5, 5, 5, 5],
          ["Влада",   4, 5, 3, 4, 5, 4],
          ["Гордана", 5, 5, 5, 5, 5, 5],
          ["Дејан",   3, 4, 2, 3, 3, 4],
          ["Ђорђе",   4, 5, 3, 4, 5, 4],
          ["Елена",   3, 3, 3, 4, 2, 3],
          ["Жаклина", 5, 5, 4, 5, 4, 5],
          ["Зоран",   4, 5, 4, 4, 3, 5],
          ["Ивана",   2, 2, 2, 2, 2, 5],
          ["Јасна",   3, 4, 5, 4, 5, 5]]
ocene = pd.DataFrame(razred)
ocene.columns=["Име", "Српски", "Енглески", "Математика", "Физика", "Хемија", "Ликовно"]
ocene1 = ocene.set_index("Име")
ocene1

У овом низу наредни смо пров увезли библиотеку _pandas_ са скраћеним именом "pd", од листе података смо направили табелу, тали колонама имена и индексирали смо табелу по имену ученика.

Као што смо раније видели, лако можемо да израчунамо просек оцена сваког ученика и да те податке испишемо. Међутим, ако желимо да просеке запамтимо у табели, треба нам нова колона. Нова колона се табели додаје тако што се просто напише:

In [ ]:
# изврши ову ћелију
ocene1["ПросекУч"] = 0.0

Ако покушамо да непостојећој колони додамо неку вредност, систем ће сам на крај табеле додати нову колону и попунити је наведеним вредностима:

In [ ]:
# изврши ову ћелију
ocene1

Сада ћемо у једном _for_-циклусу да прођемо кроз индексну колону табеле и да за сваки ред табеле израчунамо просек бројева уписаних у колоне "Српски"--"Ликовно". (Не смемо да рачунамо просек целог реда, јер редови сада садрже и колону "ПросекУч" која не сме да се укључи у рачун просека!)

In [ ]:
# изврши ову ћелију
for ucenik in ocene1.index:
    ocene1.loc[ucenik, "ПросекУч"] = ocene1.loc[ucenik, "Српски":"Ликовно"].mean()

Ево како изгледа нова табела:

In [ ]:
# изврши ову ћелију
ocene1

Да бисмо израчунали просечну оцену за сваки предмет, додаћемо нову врсту:

In [ ]:
# изврши ову ћелију
ocene1.loc["ПросекПр"] = 0.0
ocene1

Овде треба да застанемо за тренутак и да се подсетимо да се запис облика `ocene1["ПросекУч"]` односи на колоне табеле тако да ће наредба

    ocene1["ПросекУч"] = 0.0

додати нову колону попуњену нулама, док се запис `ocene1.loc["ПросекПр"]` односи на врсте табеле, па ће наредба

    ocene1.loc["ПросекПр"] = 0.0

додати нову врсту попуњену нулама (што се и десило у примеру).

In [ ]:
# изврши ову ћелију
for predmet in ocene1.columns:
    ocene1.loc["ПросекПр", predmet] = ocene1.loc["Ана":"Јасна", predmet].mean()

In [ ]:
ocene1

## 12.2. Транспоновање табеле

Замена врста и колона табеле се зове _транспоновање_. Приликом транспоновања имена колона полазне табеле постају индекси нове табеле, док индексна колона полазне табеле постаје одређује имена колона нове табеле:

<img src = "slike/DataFrame-T.jpg">

Табела се транспонује тако што се на њу примени функција `Т` која као резултат враћа нову, транспоновану табелу. Ево примера:

In [ ]:
# изврши ову ћелију
import pandas as pd
podaci = [["Ана",     "ж", 13, 46, 160],
          ["Бојан",   "м", 14, 52, 165],
          ["Влада",   "м", 13, 47, 157],
          ["Гордана", "ж", 15, 54, 165],
          ["Дејан",   "м", 15, 56, 163],
          ["Ђорђе",   "м", 13, 45, 159],
          ["Елена",   "ж", 14, 49, 161],
          ["Жаклина", "ж", 15, 52, 164],
          ["Зоран",   "м", 15, 57, 167],
          ["Ивана",   "ж", 13, 45, 158],
          ["Јасна",   "ж", 14, 51, 162]]
tabela = pd.DataFrame(podaci)
tabela.columns=["Име", "Пол", "Старост", "Тежина", "Висина"]
tabela1=tabela.set_index("Име")

tabela2 = tabela1.T

Погледајмо сада како изгледа полазна табела и како изгледа транспонована табела, шта су им врсте, а шта колоне. Кренимо од полазне табеле:

In [ ]:
# изврши ову ћелију
tabela1

In [ ]:
# изврши ову ћелију
tabela1.index

In [ ]:
# изврши ову ћелију
tabela1.columns

А сада транспонована табела:

In [ ]:
# изврши ову ћелију
tabela2

In [ ]:
# изврши ову ћелију
tabela2.index

In [ ]:
# изврши ову ћелију
tabela2.columns

Ево поново примера са оценама:

In [ ]:
# изврши ову ћелију
razred = [["Ана",     5, 3, 5, 2, 4, 5],
          ["Бојан",   5, 5, 5, 5, 5, 5],
          ["Влада",   4, 5, 3, 4, 5, 4],
          ["Гордана", 5, 5, 5, 5, 5, 5],
          ["Дејан",   3, 4, 2, 3, 3, 4],
          ["Ђорђе",   4, 5, 3, 4, 5, 4],
          ["Елена",   3, 3, 3, 4, 2, 3],
          ["Жаклина", 5, 5, 4, 5, 4, 5],
          ["Зоран",   4, 5, 4, 4, 3, 5],
          ["Ивана",   2, 2, 2, 2, 2, 5],
          ["Јасна",   3, 4, 5, 4, 5, 5]]
ocene = pd.DataFrame(razred)
ocene.columns=["Име", "Српски", "Енглески", "Математика", "Физика", "Хемија", "Ликовно"]
ocene1 = ocene.set_index("Име")
ocene1

Како смо раније већ видели, просек оцена по предметима добијамо лако:

In [ ]:
# изврши ову ћелију
for predmet in ocene1.columns:
    print(predmet, "->", ocene1[predmet].mean())

Да бисмо добили просек оцена по ученицима, можемо да приступимо врстама табеле користећи функцију `loc` како смо то већ видели, али можемо и овако. Прво ћемо да транспонујемо табелу:

In [ ]:
# изврши ову ћелију
ocene2 = ocene1.T
ocene2

па ћемо на транспоновану табелу применти исту идеју (рачунање просека по колонама, јер су колоне транспоноване табеле заправо врсте полазне табеле.):

In [ ]:
# изврши ову ћелију
for ucenik in ocene2.columns:
    print(ucenik, "->", ocene2[ucenik].mean())

## 12.3. Задаци

**Задатак 1.** Биолози су до данас описали око два милиона врта живих бића. Сва она су подељена у пет царстава и приближан број врста живих бића по царствима је дат следећом табелом:

| Царство  | Број врста |
|--|--|
| Животиње | 1.400.000 |
| Биљке    | 290.000 |
| Гљиве    | 100.000 |
| Протисти | 200.000 |
| Монере   | 10.000 |

Додај нову врсту табели која се зове "Укупно" и у њу унеси укупан број врста. Немој рачунати ручно, већ примени функцију `sum` на одговарајућу колону табеле.

**Задатак 2.** У наредној ћелији дати су подаци о тежини (у килограмима) и дужини/висини (у центиметрима) једног дечака од његовог шестог месеца па до његових 6,5 година. Прикажи ове податке графиконом.

In [ ]:
# изврши ову ћелију
merenja   = ["6 мес", "1,5 год", "2,5 год", "3,5 год", "4,5 год", "5,5 год", "6,5 год"]
masaKG    = [5.9,     11.5,      14.8,      20.5,      22.0,      24.2,      29.0     ]
visinaCM  = [62.0,    84.0,      97.0,      115.0,     122.5,     131.5,     135.0    ]

Транспонуј табелу, тако транспонобаној табели додај нову колону, па за свако мерење (што је сада врста у новој, транспонованој табели) израчунај _BMI_ (_body mass index_) по формули:

$$\hbox{BMI} = \frac{\hbox{masa u kilogramima}}{(\hbox{visina u metrima})^2}$$

**Задатак 3.** У следећој табели су приказане највише и најниже температуре (у Целзијусима) икада измерене на континентима:

|Континент:              | Европа | Азија | Африка | Северна Америка | Јужна Америка | Аустралија | Антарктик |
|------------------------|--------|-------|--------|-----------------|---------------|------------|-----------|
|Највиша забележена темп:| 48     | 54    | 55     | 56.7            | 48.9          | 50.7       | 19.8      |
|Најнижа забележена темп:| -58.1  | -67.8 | -23.9  | -63             | -32.8         | -23        | -89.2     |

(Подаци су преузети са странице https://www.space.com/17816-earth-temperature.html). Додај нови ред овој табели па у њега упиши максимални температурни распон за сваки континент, који се добија када се од највише забележене температуре одузме најнижа забележена температура.